choco install veeam-agent -y
choco install windirstat -y
choco install franz -y
choco install rambox -y
choco install docker-desktop -y
choco install github-desktop -y
choco install postman -y
choco install vscode -y
choco install vscodium -y
choco install libreoffice-fresh -y
choco install Vivaldi -y
choco install steam -y
choco install dropbox -y
choco install pencil -y
choco install skype -y
choco install Everything -y
choco install GoogleChrome -y
choco install Firefox -y
choco install filezilla -y
choco install keepassxc -y
choco install paint.net -y
choco install putty -y
choco install notepadplusplus -y
choco install virtualbox -y
:: choco install virtualbox-guest-additions-guest.install -y
choco install qbittorrent -y
choco install jdownloader -y
choco install anydesk -y
choco install ammyy-admin -y
choco install ChocolateyGUI -y
choco install openvpn -y
choco install microsoft-edge -y
choco install microsoft-edge-insider-dev -y
choco install HeidiSQL -y
choco install dbeaver -y
choco install origin -y
choco install uplay -y
choco install epicgameslauncher -y
choco install 7zip -y
choco install virustotaluploader -y
choco install teamviewer -y
choco install ilspy -y
choco install vlc -y
choco install hashtab -y
choco install sandboxie -y
choco install git -y
choco install HxD -y
choco install lockhunter -y
choco install nodejs-lts --version 10.18.1 -y
:: choco install  -y
:: choco install  -y
:: choco install  -y
:: choco install  -y