code --install-extension akamud.vscode-theme-onelight
code --install-extension formulahendry.auto-close-tag
code --install-extension aaron-bond.better-comments
code --install-extension alefragnani.bookmarks
code --install-extension ms-dotnettools.csharp
code --install-extension jakewilson.vscode-cdnjs
code --install-extension naumovs.color-highlight
code --install-extension mihelcic.colored-regions
code --install-extension aeschli.vscode-css-formatter
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension kodetech.electron-debug
code --install-extension firefox-devtools.vscode-firefox-debug
code --install-extension msjsdiag.debugger-for-edge
code --install-extension codemooseus.vscode-devtools-for-chrome
code --install-extension joelday.docthis
code --install-extension bogdanlazar.edge
code --install-extension fisheva.eva-theme
code --install-extension thenikso.github-plus-theme
code --install-extension github.vscode-pull-request-github
code --install-extension github.github-vscode-theme
code --install-extension eamodio.gitlens
code --install-extension sidthesloth.html5-boilerplate
code --install-extension zignd.html-css-class-completion
code --install-extension dbaeumer.jshint
code --install-extension nickdemayo.vscode-json-editor
code --install-extension yzhang.markdown-all-in-one
code --install-extension yzane.markdown-pdf
code --install-extension fms-cat.theme-monokaisharp
code --install-extension abax.nearest-icons
code --install-extension eg2.vscode-npm-script
code --install-extension azemoh.one-monokai
code --install-extension christian-kohler.path-intellisense
code --install-extension mohsen1.prettify-json
code --install-extension ms-python.python
code --install-extension njpwerner.autodocstring
code --install-extension cssho.vscode-svgviewer
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension pmneo.tsimporter
code --install-extension jamiewest.theme-light-vs-mac
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension vscode-icons-team.vscode-icons
code --install-extension tomoki1207.pdf
code --install-extension dotjoshjohnson.xml
code --install-extension mhutchie.git-graph
code --install-extension ms-edgedevtools.vscode-edge-devtools
code --install-extension cantonios.project-templates
