pacaur -S postman-bin --noconfirm --noedit
pacaur -S franz-bin --noconfirm --noedit
pacaur -S spotify --noconfirm --noedit
pacaur -S visual-studio-code-bin --noconfirm --noedit
pacaur -S discord --noconfirm --noedit
pacaur -S google-chrome --noconfirm --noedit
pacaur -S android-studio --noconfirm --noedit
pacaur -S tor-browser --noconfirm --noedit
pacaur -S skypeforlinux-stable-bin --noconfirm --noedit
pacaur -S vivaldi --noconfirm --noedit
pacaur -S dropbox --noconfirm --noedit
pacaur -S ungoogled-chromium --noconfirm --noedit
pacaur -S teamviewer --noconfirm --noedit
pacaur -S ttf-ms-fonts --noconfirm --noedit
pacaur -S etcher-bin --noconfirm --noedit
pacaur -S vmware-workstation --noconfirm --noedit
pacaur -S slack-desktop --noconfirm --noedit
pacaur -S tor-browser-en --noconfirm --noedit
pacaur -S jdownloader2 --noconfirm --noedit
pacaur -S telegram-desktop-bin --noconfirm --noedit
pacaur -S github-desktop --noconfirm --noedit
